meta:
  id: recipe
  file-extension: tbl
  encoding: utf-8
  endian: le
seq:
  - id: table
    type: header
  - id: rows
    type: row
    repeat: expr
    repeat-expr: table.row_count
  - id: strings
    type: strz
    repeat: expr
    repeat-expr: table.unique_strings_count
types:
  header:
    seq:
      - id: version
        type: s4
      - id: descriptors_hash
        type: u4
      - id: layout_hash
        type: u4
      - id: table_version
        type: s4
      - id: row_count
        type: s4
      - id: string_data_size
        type: s4
      - id: unique_strings_count
        type: s4
  row:
    seq:
      - id: recipe_id
        type: s4
      - id: product_item_id
        size: 16
      - id: base_material_id
        size: 16
      - id: ui_name
        type: s4
      - id: ui_usage
        type: s4
      - id: ui_stats
        type: s4
      - id: max_yield
        type: s4
