meta:
  id: inventory
  file-extension: tbl
  encoding: utf-8
  endian: le
seq:
  - id: table
    type: header
  - id: rows
    type: row
    repeat: expr
    repeat-expr: table.row_count
  - id: strings
    type: strz
    repeat: expr
    repeat-expr: table.unique_strings_count
types:
  header:
    seq:
      - id: version
        type: s4
      - id: descriptors_hash
        type: u4
      - id: layout_hash
        type: u4
      - id: table_version
        type: s4
      - id: row_count
        type: s4
      - id: string_data_size
        type: s4
      - id: unique_strings_count
        type: s4
  row:
    seq:
      - id: inventory_id
        size: 16
      - id: inventory_name
        type: s4
      - id: read_only
        type: s1
      - id: restock_interval
        type: f4
      - id: max_items
        type: s4
